services:
  mongo:
    image: mongo:6.0
    container_name: mountain-trails-storage
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: trails
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
