@URL=http://localhost:5000/api

# @name session
GET {{URL}}/users

# @ref session
GET {{URL}}/users/test

# @ref session
POST {{URL}}/users/login
Content-Type: application/json
{
    "nick": "test",
    "password": "test"
}

# @ref session
POST {{URL}}/users/refresh-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2IzMTdlZjVjMzQ3MDAzZGM0ZGEyODEiLCJuaWNrIjoidGVzdCIsImlhdCI6MTc0MDkxMTQwNCwiZXhwIjoxNzQwOTEyMDA0fQ.ZOjjsKUbz0A-UuncjTL41ytQfDxEK34_jD9rwKh8um0
