@URL=http://localhost:5000/api

# @name session
GET {{URL}}/users?page=1&limit=1

# @ref session
GET {{URL}}/users/ka3wo/peaks?next=67a8d45ad7c8db5a27b2ed53

# @ref session
GET {{URL}}/users/test

# @ref session
POST {{URL}}/users/login
Content-Type: application/json
{
    "nick": "test",
    "password": "test"
}

# @ref session
POST {{URL}}/users/refresh-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2IzMTdlZjVjMzQ3MDAzZGM0ZGEyODEiLCJuaWNrIjoidGVzdCIsImlhdCI6MTc0MDkxMTQwNCwiZXhwIjoxNzQwOTEyMDA0fQ.ZOjjsKUbz0A-UuncjTL41ytQfDxEK34_jD9rwKh8um0

# @ref session
POST {{URL}}/users/test/peaks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2IzMTdlZjVjMzQ3MDAzZGM0ZGEyODEiLCJuaWNrIjoidGVzdCIsImlhdCI6MTc0MDk5ODgyMywiZXhwIjoxNzQwOTk4ODgzfQ.TL5Emn7mv3LwHkOC5b1K6hVsDgHF51urSnJqrS7_-ek 
{
    "peakId": "67a8d45ad7c8db5a27b28e50"
}

###
### Mapa Turystyczna Route Request
POST https://mapa-turystyczna.pl/widget/route
Content-Type: application/x-www-form-urlencoded

route_query=49.4390940,20.4854140;49.4251380,20.4825950&route_type=v=foot,m=hiking&event_category=Route+details&display_label=true
